General:
    folds: "./temp/tmb_7cancer_10x_5fold_3247.csv"
    target_col: "label"
    epochs: &epochs 30
    num_folds: 1
    num_classes: 2
    cross_validation: True
    eval_interval: 1
    seed: 202201


Data:
    dataset:
        name: "GraphDataset"
        feat_dir: "./tcga10x_graph"

    dataloader:
        batch_size: 1
        num_workers: 4


Model:
    base: "PatchGCN"
    params: {'input_dim':2048, 'num_layers': 4, 'edge_agg': 'spatial', 'resample': 0, 'n_classes': 2}


Optimizer:
    optimizer:
        name: Adam
        params:
            lr: 0.001
            amsgrad: False
    lr_scheduler:
        name: CosineAnnealingLR
        params:
            T_max: *epochs
            last_epoch: -1

Loss:
    base_loss:
        name: "CrossEntropyLoss"

